version: "3.9"

services:
  users:
    build: ./users
    ports:
      - "3001:3000"
    depends_on: 
      - store
    networks:
      - app-network

  store:
    build: ./store
    ports:
      - "3002:3000"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "5000:443"
    depends_on:
      - users
      - store
    networks:
      - app-network

networks:
  app-network:
